spring:
  config:
    activate:
      on-profile: local

com:
  setvect:
    bokslcoin:
      autotrading:
        enable: false
        api:
          # 엑세스 키: 환경 변수 또는 직접 입력
          accessKey: ${ACCESS_KEY}
          # 보안 키: 환경 변수 또는 직접 입력
          secretKey: ${SECRET_KEY}
          url: https://api.upbit.com
        schedule:
          # 시황 체크 주기
          fixedDelay: 10000
        algorithm:
          # 매매 알고리즘 지정
          name: vbs # vbs, vbsStop
          # 변동성 돌파 알고리즘 관련 설정값
          vbs:
            # 매수, 매도 대상 코인
            coin: KRW-BTC
            # 변동성 돌파 판단 비율
            k: 0.5
            # 총 현금을 기준으로 투자 비율. 1은 전액, 0.5은 50% 투자
            rate: 0.5

          # 변동성 돌파 알고리즘 관련 설정값
          vbsStop:
            # 매수, 매도 대상 코인
            market: KRW-BTC
            # 변동성 돌파 판단 비율
            k: 0.5
            # 총 현금을 기준으로 투자 비율. 1은 전액, 0.5은 50% 투자
            rate: 0.5
            # 손절 매도
            loseStop: 0.05
            # 익절 매도
            gainStop: 0.1
            # 매매 주기(P_60, P_240, P_1440)
            tradePeriod: P_60

---
