spring:
  config:
    activate:
      on-profile: local

com:
  setvect:
    bokslcoin:
      autotrading:
        api:
          # 엑세스 키: 환경 변수로 입력
          accessKey: ${ACCESS_KEY}
          # 보안 키: 환경 변수로 입력
          secretKey: ${SECRET_KEY}
          url: https://api.upbit.com
        schedule:
          # 시황 체크 주기
          fixedDelay: 5000
        algorithm:
          # 매매 알고리즘 지정
          name: vbs
          # 변동성 돌파 알고리즘 관련 설정값
          vbs:
            coin: KRW-BTC
            k: 0.5

---
