spring:
  config:
    activate:
      on-profile: local

com:
  setvect:
    bokslcoin:
      autotrading:
        # true 매매 진행, false면 매매를 포함한 시세 확인을 하지 않음
        enable: false
        api:
          # 엑세스 키: 환경 변수 또는 직접 입력
          accessKey: ${ACCESS_KEY}
          # 보안 키: 환경 변수 또는 직접 입력
          secretKey: ${SECRET_KEY}
          url: https://api.upbit.com
        schedule:
          # 시세 체크 주기
          fixedDelay: 10000
        algorithm:
          # 매매 알고리즘 지정
          name: vbsTrailingStop # vbs, vbsStop, vbsTrailingStop
          # 변동성 돌파 알고리즘 관련 설정값
          vbs:
            # 매수, 매도 대상 코인
            coin: KRW-BTC
            # 변동성 돌파 판단 비율
            k: 0.5
            # 총 현금을 기준으로 투자 비율. 1은 전액, 0.5은 50% 투자
            rate: 0.5

          # 변동성 돌파 + 손절/익절 알고리즘 관련 설정값
          vbsStop:
            # 매수, 매도 대상 코인
            market: KRW-BTC
            # 변동성 돌파 판단 비율
            k: 0.5
            # 총 현금을 기준으로 투자 비율. 1은 전액, 0.5은 50% 투자
            investRatio: 0.5
            # 손절 매도
            loseStopRate: 0.05
            # 익절 매도
            gainStopRate: 0.1
            # 매매 주기(P_60, P_240, P_1440)
            tradePeriod: P_1440

          # 변동성 돌파 + 손절 + 트레일링 스탑 알고리즘 관련 설정값
          vbsTrailingStop:
            # 매수, 매도 대상 코인
            market: KRW-BTC
            # 변동성 돌파 판단 비율
            k: 0.5
            # 총 현금을 기준으로 투자 비율. 1은 전액, 0.5은 50% 투자
            investRatio: 0.5
            # 손절 매도
            loseStopRate: 0.05
            # 트레일링 스탑 진입점
            gainStopRate: 0.03
            # gainStopRate 이상 상승 후 전고점 대비 trailingStopRate 비율 만큼 하락하면 시장가 매도
            # 예를 들어 trailingStopRate 값이 0.02일 때 고점 수익률이 12%인 상태에서 10%미만으로 떨어지면 시장가 매도
            trailingStopRate: 0.02
            # 매매 주기(P_60, P_240, P_1440)
            tradePeriod: P_1440

        slack:
          # 이벤트 발생시 슬랙메시지 전달 여부
          # 만약 슬렉 메시지를 받고 싶지 않으면 false로 셋팅 후 항목 token, channelId 값을 비워둠
          enable: false
          # 'xoxb'로 시작하는 슬렉 App oAuth Key
          token:
          # 메시지 전달 채널 ID
          channelId:
